# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from qt.customSlider._generic_range_slider import _GenericRangeSlider

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.main_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.bottom_frame = QtWidgets.QFrame(self.main_frame)
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_Pitch = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Pitch.setFont(font)
        self.radioButton_Pitch.setStyleSheet("")
        self.radioButton_Pitch.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_Pitch.setObjectName("radioButton_Pitch")
        self.gridLayout_5.addWidget(self.radioButton_Pitch, 1, 0, 1, 1)
        self.radioButton_CloseUp = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_CloseUp.setFont(font)
        self.radioButton_CloseUp.setStyleSheet("")
        self.radioButton_CloseUp.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_CloseUp.setObjectName("radioButton_CloseUp")
        self.gridLayout_5.addWidget(self.radioButton_CloseUp, 0, 0, 1, 1)
        self.radioButton_Hit = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Hit.setFont(font)
        self.radioButton_Hit.setStyleSheet("")
        self.radioButton_Hit.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_Hit.setObjectName("radioButton_Hit")
        self.gridLayout_5.addWidget(self.radioButton_Hit, 2, 0, 1, 1)
        self.radioButton_Overlook = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Overlook.setFont(font)
        self.radioButton_Overlook.setStyleSheet("")
        self.radioButton_Overlook.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_Overlook.setObjectName("radioButton_Overlook")
        self.gridLayout_5.addWidget(self.radioButton_Overlook, 3, 0, 1, 1)
        self.radioButton_Other = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Other.setFont(font)
        self.radioButton_Other.setStyleSheet("")
        self.radioButton_Other.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_Other.setObjectName("radioButton_Other")
        self.gridLayout_5.addWidget(self.radioButton_Other, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.line_4 = QtWidgets.QFrame(self.bottom_frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.frame_5 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_5)
        self.line_5 = QtWidgets.QFrame(self.bottom_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.frame_3 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_split_clip = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_split_clip.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_split_clip.setFont(font)
        self.pushButton_split_clip.setStyleSheet("background-color: lightgreen;")
        self.pushButton_split_clip.setObjectName("pushButton_split_clip")
        self.gridLayout_4.addWidget(self.pushButton_split_clip, 1, 0, 1, 1)
        self.pushButton_next_clip = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_next_clip.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_next_clip.setFont(font)
        self.pushButton_next_clip.setStyleSheet("background-color: lightgreen;")
        self.pushButton_next_clip.setObjectName("pushButton_next_clip")
        self.gridLayout_4.addWidget(self.pushButton_next_clip, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.bottom_frame, 4, 0, 1, 1)
        self.center_frame = QtWidgets.QFrame(self.main_frame)
        self.center_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_frame.setObjectName("center_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.center_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.center_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_start_frame = QtWidgets.QLabel(self.frame)
        self.label_start_frame.setMinimumSize(QtCore.QSize(320, 240))
        self.label_start_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_start_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.label_start_frame.setObjectName("label_start_frame")
        self.verticalLayout.addWidget(self.label_start_frame)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_start_frame_prev = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start_frame_prev.setFont(font)
        self.pushButton_start_frame_prev.setObjectName("pushButton_start_frame_prev")
        self.horizontalLayout_3.addWidget(self.pushButton_start_frame_prev)
        self.lineEdit_start_frame = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_start_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_start_frame.setFont(font)
        self.lineEdit_start_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_start_frame.setObjectName("lineEdit_start_frame")
        self.horizontalLayout_3.addWidget(self.lineEdit_start_frame)
        self.pushButton_start_frame_next = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start_frame_next.setFont(font)
        self.pushButton_start_frame_next.setObjectName("pushButton_start_frame_next")
        self.horizontalLayout_3.addWidget(self.pushButton_start_frame_next)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.center_frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.frame_8 = QtWidgets.QFrame(self.center_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton_clip_prev = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clip_prev.setFont(font)
        self.pushButton_clip_prev.setObjectName("pushButton_clip_prev")
        self.horizontalLayout_5.addWidget(self.pushButton_clip_prev)
        self.pushButton_clip_play = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clip_play.setFont(font)
        self.pushButton_clip_play.setObjectName("pushButton_clip_play")
        self.horizontalLayout_5.addWidget(self.pushButton_clip_play)
        self.pushButton_clip_next = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clip_next.setFont(font)
        self.pushButton_clip_next.setObjectName("pushButton_clip_next")
        self.horizontalLayout_5.addWidget(self.pushButton_clip_next)
        self.lineEdit_clip = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_clip.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_clip.setFont(font)
        self.lineEdit_clip.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_clip.setObjectName("lineEdit_clip")
        self.horizontalLayout_5.addWidget(self.lineEdit_clip)
        self.pushButton_clip_1x = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_clip_1x.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clip_1x.setFont(font)
        self.pushButton_clip_1x.setObjectName("pushButton_clip_1x")
        self.horizontalLayout_5.addWidget(self.pushButton_clip_1x)
        self.pushButton_clip_2x = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_clip_2x.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clip_2x.setFont(font)
        self.pushButton_clip_2x.setObjectName("pushButton_clip_2x")
        self.horizontalLayout_5.addWidget(self.pushButton_clip_2x)
        self.pushButton_clip_4x = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_clip_4x.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clip_4x.setFont(font)
        self.pushButton_clip_4x.setObjectName("pushButton_clip_4x")
        self.horizontalLayout_5.addWidget(self.pushButton_clip_4x)
        self.pushButton_clip_8x = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_clip_8x.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clip_8x.setFont(font)
        self.pushButton_clip_8x.setObjectName("pushButton_clip_8x")
        self.horizontalLayout_5.addWidget(self.pushButton_clip_8x)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout_2.addWidget(self.frame_9, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 0, 0, 1, 1)
        self.label_clip = QtWidgets.QLabel(self.frame_8)
        self.label_clip.setMinimumSize(QtCore.QSize(900, 500))
        self.label_clip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_clip.setObjectName("label_clip")
        self.gridLayout_2.addWidget(self.label_clip, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.line_2 = QtWidgets.QFrame(self.center_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.frame_6 = QtWidgets.QFrame(self.center_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.label_end_frame = QtWidgets.QLabel(self.frame_6)
        self.label_end_frame.setMinimumSize(QtCore.QSize(320, 240))
        self.label_end_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.label_end_frame.setObjectName("label_end_frame")
        self.verticalLayout_2.addWidget(self.label_end_frame)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pushButton_end_frame_prev = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_end_frame_prev.setFont(font)
        self.pushButton_end_frame_prev.setObjectName("pushButton_end_frame_prev")
        self.horizontalLayout_4.addWidget(self.pushButton_end_frame_prev)
        self.lineEdit_end_frame = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_end_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_end_frame.setFont(font)
        self.lineEdit_end_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_end_frame.setObjectName("lineEdit_end_frame")
        self.horizontalLayout_4.addWidget(self.lineEdit_end_frame)
        self.pushButton_end_frame_next = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_end_frame_next.setFont(font)
        self.pushButton_end_frame_next.setObjectName("pushButton_end_frame_next")
        self.horizontalLayout_4.addWidget(self.pushButton_end_frame_next)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_2.addWidget(self.frame_7)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.gridLayout.addWidget(self.center_frame, 1, 0, 1, 1)
        
        # self.horizontalSlider = _GenericRangeSlider[int](self.main_frame)
        # self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider.setTickPosition(_GenericRangeSlider[int].TicksBelow)
        # self.horizontalSlider.setObjectName("horizontalSlider")

        self.horizontalSlider = QtWidgets.QSlider(self.main_frame)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.gridLayout.addWidget(self.horizontalSlider, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.main_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.main_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuProject.addAction(self.actionNew)
        self.menuProject.addAction(self.actionLoad)
        self.menubar.addAction(self.menuProject.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_Pitch.setText(_translate("MainWindow", "Pitch"))
        self.radioButton_CloseUp.setText(_translate("MainWindow", "CloseUp"))
        self.radioButton_Hit.setText(_translate("MainWindow", "Hit"))
        self.radioButton_Overlook.setText(_translate("MainWindow", "Overlook"))
        self.radioButton_Other.setText(_translate("MainWindow", "Other"))
        self.label.setText(_translate("MainWindow", "Class"))
        self.pushButton_split_clip.setText(_translate("MainWindow", "Split Clip"))
        self.pushButton_next_clip.setText(_translate("MainWindow", "Next Clip"))
        self.label_start_frame.setText(_translate("MainWindow", "Start Frame"))
        self.pushButton_start_frame_prev.setText(_translate("MainWindow", "Prev"))
        self.pushButton_start_frame_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_clip_prev.setText(_translate("MainWindow", "Prev"))
        self.pushButton_clip_play.setText(_translate("MainWindow", "Play"))
        self.pushButton_clip_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_clip_1x.setText(_translate("MainWindow", "1X"))
        self.pushButton_clip_2x.setText(_translate("MainWindow", "2X"))
        self.pushButton_clip_4x.setText(_translate("MainWindow", "4X"))
        self.pushButton_clip_8x.setText(_translate("MainWindow", "8X"))
        self.label_clip.setText(_translate("MainWindow", "Clip"))
        self.label_end_frame.setText(_translate("MainWindow", "End Frame"))
        self.pushButton_end_frame_prev.setText(_translate("MainWindow", "Prev"))
        self.pushButton_end_frame_next.setText(_translate("MainWindow", "Next"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.actionOpen.setText(_translate("MainWindow", "&Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
