# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\NewProject.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewProject(object):
    def setupUi(self, NewProject):
        NewProject.setObjectName("NewProject")
        NewProject.resize(375, 475)
        NewProject.setMinimumSize(QtCore.QSize(375, 475))
        NewProject.setMaximumSize(QtCore.QSize(375, 475))
        self.gridLayoutWidget = QtWidgets.QWidget(NewProject)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(7, 10, 361, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Open = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Open.sizePolicy().hasHeightForWidth())
        self.pushButton_Open.setSizePolicy(sizePolicy)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.gridLayout.addWidget(self.pushButton_Open, 5, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_dir_path = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_dir_path.sizePolicy().hasHeightForWidth())
        self.img_dir_path.setSizePolicy(sizePolicy)
        self.img_dir_path.setMinimumSize(QtCore.QSize(150, 0))
        self.img_dir_path.setMaximumSize(QtCore.QSize(150, 16777215))
        self.img_dir_path.setObjectName("img_dir_path")
        self.horizontalLayout.addWidget(self.img_dir_path)
        self.pushButton_img_dir = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_img_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_img_dir.setSizePolicy(sizePolicy)
        self.pushButton_img_dir.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_img_dir.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_img_dir.setObjectName("pushButton_img_dir")
        self.horizontalLayout.addWidget(self.pushButton_img_dir)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.shot_detection_result_path = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_detection_result_path.sizePolicy().hasHeightForWidth())
        self.shot_detection_result_path.setSizePolicy(sizePolicy)
        self.shot_detection_result_path.setMinimumSize(QtCore.QSize(150, 0))
        self.shot_detection_result_path.setMaximumSize(QtCore.QSize(150, 16777215))
        self.shot_detection_result_path.setObjectName("shot_detection_result_path")
        self.horizontalLayout_2.addWidget(self.shot_detection_result_path)
        self.pushButton_shot_detection_result = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_shot_detection_result.sizePolicy().hasHeightForWidth())
        self.pushButton_shot_detection_result.setSizePolicy(sizePolicy)
        self.pushButton_shot_detection_result.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_shot_detection_result.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_shot_detection_result.setObjectName("pushButton_shot_detection_result")
        self.horizontalLayout_2.addWidget(self.pushButton_shot_detection_result)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.output_dir_path = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_dir_path.sizePolicy().hasHeightForWidth())
        self.output_dir_path.setSizePolicy(sizePolicy)
        self.output_dir_path.setMinimumSize(QtCore.QSize(150, 0))
        self.output_dir_path.setMaximumSize(QtCore.QSize(150, 16777215))
        self.output_dir_path.setObjectName("output_dir_path")
        self.horizontalLayout_3.addWidget(self.output_dir_path)
        self.pushButton_output_dir = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_output_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_output_dir.setSizePolicy(sizePolicy)
        self.pushButton_output_dir.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_output_dir.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_output_dir.setObjectName("pushButton_output_dir")
        self.horizontalLayout_3.addWidget(self.pushButton_output_dir)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 2, 1, 1)

        self.retranslateUi(NewProject)
        QtCore.QMetaObject.connectSlotsByName(NewProject)

    def retranslateUi(self, NewProject):
        _translate = QtCore.QCoreApplication.translate
        NewProject.setWindowTitle(_translate("NewProject", "NewProject"))
        self.pushButton_Open.setText(_translate("NewProject", "Open"))
        self.pushButton_img_dir.setText(_translate("NewProject", "..."))
        self.label_2.setText(_translate("NewProject", "<html><head/><body><p>Shot Detection Result</p><p>(scenes.txt)</p></body></html>"))
        self.pushButton_Cancel.setText(_translate("NewProject", "Cancel"))
        self.pushButton_shot_detection_result.setText(_translate("NewProject", "..."))
        self.label_1.setText(_translate("NewProject", "Image Directory Path"))
        self.pushButton_output_dir.setText(_translate("NewProject", "..."))
        self.label_3.setText(_translate("NewProject", "<html><head/><body><p>Output Directory Path</p></body></html>"))
